DebugLevel: NONE

# if enabled, you can break other graves with permission:
# GraveStonesPlus.BreakOtherGraves
BreakOtherGravesWithPermission: false

# List of worlds with graves disabled
DisabledWorlds: []

# Enable a glowing effect near grave
GlowingEffectNearGrave: true
# Distance for glowing effect
GlowingEffectDistance: 30