name: ${project.name}
version: "${project.version}"
main: com.bencodez.gravestonesplus.GraveStonesPlus
description: Description
author: BenCodez
api-version: 1.13
libraries:
  - org.openjdk.nashorn:nashorn-core:15.3
softdepend: [ProtocolLib, Vault, PvPManager]
commands:
  gravestonesplus:
    description: Main plugin command
permissions:
  GraveStonesPlus.BreakOtherGraves:
    description: Allows you to break other graves
  GraveStonesPlus.AllowGrave:
    description: Permission to have graves
    default: true
    